@echo off
echo 🧹 Limpando cache do Next.js...
rmdir /s /q .next 2>nul

echo 🗑️ Limpando node_modules/.cache...
rmdir /s /q node_modules\.cache 2>nul

echo 🚀 Iniciando servidor de desenvolvimento...
npm run dev
